# Generated by Django 2.1.2 on 2019-01-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='certifications',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='courses',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='education',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='git_hub_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
