# Generated by Django 2.1.2 on 2019-01-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20190119_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
