# Generated by Django 2.1.2 on 2019-01-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_portfolio_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='summery',
            new_name='summary',
        ),
    ]
