# Generated by Django 2.1.2 on 2019-01-19 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20190119_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certifications', models.CharField(blank=True, max_length=500)),
                ('Verify', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='certifications',
        ),
        migrations.AddField(
            model_name='certifications',
            name='por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Portfolio'),
        ),
    ]
