# Generated by Django 2.1.2 on 2019-01-19 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20190119_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.TextField()),
                ('Number', models.BigIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='skills',
        ),
        migrations.AddField(
            model_name='skills',
            name='por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Portfolio'),
        ),
        migrations.AddField(
            model_name='courses',
            name='por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Portfolio'),
        ),
    ]
